version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: ResourceFinder.Tests/Dockerfile.dev
    command: ['dotnet', 'test', './ResourceFinder.Tests']

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ResourceFinder/Dockerfile.dev

  client:
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./ResourceWeb
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./ResourceWeb:/app

  nginx:
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4005:80'
